name: Build and Push WebWake Docker Image

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner for the build

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  # Check out the repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Setup Docker Buildx to build images

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}  # GitHub username
        password: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:latest .  # Build the image

    - name: Push Docker image to GitHub Packages
      run: |
        docker push ghcr.io/${{ github.repository }}:latest  # Push the image to GitHub Packages